# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aruba-iot-types.proto',
  package='aruba_telemetry',
  serialized_pb=_b('\n\x15\x61ruba-iot-types.proto\x12\x0f\x61ruba_telemetry\"\x83\x01\n\x04Meta\x12\x0f\n\x07version\x18\x01 \x02(\x04\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12)\n\x07nbTopic\x18\x03 \x01(\x0e\x32\x18.aruba_telemetry.NbTopic\x12)\n\x07sbTopic\x18\x04 \x01(\x0e\x32\x18.aruba_telemetry.SbTopic*\xce\x02\n\x0f\x64\x65viceClassEnum\x12\x10\n\x0cunclassified\x10\x00\x12\x0f\n\x0b\x61rubaBeacon\x10\x01\x12\x0c\n\x08\x61rubaTag\x10\x02\x12\t\n\x05zfTag\x10\x03\x12\x0e\n\nstanleyTag\x10\x04\x12\x10\n\x0cvirginBeacon\x10\x05\x12\x11\n\renoceanSensor\x10\x06\x12\x11\n\renoceanSwitch\x10\x07\x12\x0b\n\x07iBeacon\x10\x08\x12\x0e\n\nallBleData\x10\t\x12\x0e\n\nRawBleData\x10\n\x12\r\n\teddystone\x10\x0b\x12\r\n\tassaAbloy\x10\x0c\x12\x0f\n\x0b\x61rubaSensor\x10\r\x12\r\n\tabbSensor\x10\x0e\x12\x0b\n\x07wifiTag\x10\x0f\x12\x10\n\x0cwifiAssocSta\x10\x10\x12\x12\n\x0ewifiUnassocSta\x10\x11\x12\x0c\n\x08mysphera\x10\x12\x12\x0b\n\x07sBeacon\x10\x13*}\n\nActionType\x12\x0e\n\nbleConnect\x10\x00\x12\x11\n\rbleDisconnect\x10\x01\x12\x0c\n\x08gattRead\x10\x02\x12\r\n\tgattWrite\x10\x03\x12\x19\n\x15gattWriteWithResponse\x10\x04\x12\x14\n\x10gattNotification\x10\x05*x\n\x07NbTopic\x12\r\n\ttelemetry\x10\x00\x12\x11\n\ractionResults\x10\x01\x12\x13\n\x0f\x63haracteristics\x10\x02\x12\x0b\n\x07\x62leData\x10\x03\x12\x0c\n\x08wifiData\x10\x04\x12\x0f\n\x0b\x64\x65viceCount\x10\x05\x12\n\n\x06status\x10\x06*0\n\x07SbTopic\x12\x0b\n\x07\x61\x63tions\x10\x00\x12\n\n\x06\x63onfig\x10\x01\x12\x0c\n\x08sbStatus\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DEVICECLASSENUM = _descriptor.EnumDescriptor(
  name='deviceClassEnum',
  full_name='aruba_telemetry.deviceClassEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='unclassified', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='arubaBeacon', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='arubaTag', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='zfTag', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='stanleyTag', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='virginBeacon', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='enoceanSensor', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='enoceanSwitch', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='iBeacon', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='allBleData', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RawBleData', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eddystone', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='assaAbloy', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='arubaSensor', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='abbSensor', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='wifiTag', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='wifiAssocSta', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='wifiUnassocSta', index=17, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='mysphera', index=18, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sBeacon', index=19, number=19,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=177,
  serialized_end=511,
)
_sym_db.RegisterEnumDescriptor(_DEVICECLASSENUM)

deviceClassEnum = enum_type_wrapper.EnumTypeWrapper(_DEVICECLASSENUM)
_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='aruba_telemetry.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='bleConnect', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bleDisconnect', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gattRead', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gattWrite', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gattWriteWithResponse', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gattNotification', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=513,
  serialized_end=638,
)
_sym_db.RegisterEnumDescriptor(_ACTIONTYPE)

ActionType = enum_type_wrapper.EnumTypeWrapper(_ACTIONTYPE)
_NBTOPIC = _descriptor.EnumDescriptor(
  name='NbTopic',
  full_name='aruba_telemetry.NbTopic',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='telemetry', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='actionResults', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='characteristics', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bleData', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='wifiData', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='deviceCount', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='status', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=640,
  serialized_end=760,
)
_sym_db.RegisterEnumDescriptor(_NBTOPIC)

NbTopic = enum_type_wrapper.EnumTypeWrapper(_NBTOPIC)
_SBTOPIC = _descriptor.EnumDescriptor(
  name='SbTopic',
  full_name='aruba_telemetry.SbTopic',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='actions', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='config', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sbStatus', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=762,
  serialized_end=810,
)
_sym_db.RegisterEnumDescriptor(_SBTOPIC)

SbTopic = enum_type_wrapper.EnumTypeWrapper(_SBTOPIC)
unclassified = 0
arubaBeacon = 1
arubaTag = 2
zfTag = 3
stanleyTag = 4
virginBeacon = 5
enoceanSensor = 6
enoceanSwitch = 7
iBeacon = 8
allBleData = 9
RawBleData = 10
eddystone = 11
assaAbloy = 12
arubaSensor = 13
abbSensor = 14
wifiTag = 15
wifiAssocSta = 16
wifiUnassocSta = 17
mysphera = 18
sBeacon = 19
bleConnect = 0
bleDisconnect = 1
gattRead = 2
gattWrite = 3
gattWriteWithResponse = 4
gattNotification = 5
telemetry = 0
actionResults = 1
characteristics = 2
bleData = 3
wifiData = 4
deviceCount = 5
status = 6
actions = 0
config = 1
sbStatus = 2



_META = _descriptor.Descriptor(
  name='Meta',
  full_name='aruba_telemetry.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='aruba_telemetry.Meta.version', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='access_token', full_name='aruba_telemetry.Meta.access_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nbTopic', full_name='aruba_telemetry.Meta.nbTopic', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sbTopic', full_name='aruba_telemetry.Meta.sbTopic', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=174,
)

_META.fields_by_name['nbTopic'].enum_type = _NBTOPIC
_META.fields_by_name['sbTopic'].enum_type = _SBTOPIC
DESCRIPTOR.message_types_by_name['Meta'] = _META
DESCRIPTOR.enum_types_by_name['deviceClassEnum'] = _DEVICECLASSENUM
DESCRIPTOR.enum_types_by_name['ActionType'] = _ACTIONTYPE
DESCRIPTOR.enum_types_by_name['NbTopic'] = _NBTOPIC
DESCRIPTOR.enum_types_by_name['SbTopic'] = _SBTOPIC

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
  DESCRIPTOR = _META,
  __module__ = 'aruba_iot_types_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.Meta)
  ))
_sym_db.RegisterMessage(Meta)


# @@protoc_insertion_point(module_scope)