# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-sb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import aruba_iot_types_pb2 as aruba__iot__types__pb2
import aruba_iot_sb_action_pb2 as aruba__iot__sb__action__pb2
import aruba_iot_sb_config_pb2 as aruba__iot__sb__config__pb2
import aruba_iot_sb_status_pb2 as aruba__iot__sb__status__pb2
import aruba_iot_sb_zb_pb2 as aruba__iot__sb__zb__pb2
import aruba_iot_sb_serial_data_pb2 as aruba__iot__sb__serial__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61ruba-iot-sb.proto\x12\x0f\x61ruba_telemetry\x1a\x15\x61ruba-iot-types.proto\x1a\x19\x61ruba-iot-sb-action.proto\x1a\x19\x61ruba-iot-sb-config.proto\x1a\x19\x61ruba-iot-sb-status.proto\x1a\x15\x61ruba-iot-sb-zb.proto\x1a\x1e\x61ruba-iot-sb-serial-data.proto\"&\n\x08Receiver\x12\x0b\n\x03\x61ll\x18\x01 \x01(\x08\x12\r\n\x05\x61pMac\x18\x02 \x01(\x0c\"\xc6\x02\n\x0cIotSbMessage\x12#\n\x04meta\x18\x01 \x02(\x0b\x32\x15.aruba_telemetry.Meta\x12+\n\x08receiver\x18\x02 \x01(\x0b\x32\x19.aruba_telemetry.Receiver\x12(\n\x07\x61\x63tions\x18\x03 \x03(\x0b\x32\x17.aruba_telemetry.Action\x12\x30\n\x06\x63onfig\x18\x04 \x01(\x0b\x32 .aruba_telemetry.TransportConfig\x12.\n\x06status\x18\x05 \x01(\x0b\x32\x1e.aruba_telemetry.ConnectStatus\x12(\n\x06zigbee\x18\x06 \x01(\x0b\x32\x18.aruba_telemetry.SbZbMsg\x12.\n\x07sbSData\x18\x07 \x03(\x0b\x32\x1d.aruba_telemetry.SbSerialData')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aruba_iot_sb_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECEIVER']._serialized_start=198
  _globals['_RECEIVER']._serialized_end=236
  _globals['_IOTSBMESSAGE']._serialized_start=239
  _globals['_IOTSBMESSAGE']._serialized_end=565
# @@protoc_insertion_point(module_scope)
