# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-nb-wifi-data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import aruba_iot_types_pb2 as aruba__iot__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61ruba-iot-nb-wifi-data.proto\x12\x0f\x61ruba_telemetry\x1a\x15\x61ruba-iot-types.proto\"r\n\x08WiFiData\x12\x0b\n\x03mac\x18\x01 \x01(\x0c\x12\x35\n\x0b\x64\x65viceClass\x18\x02 \x03(\x0e\x32 .aruba_telemetry.deviceClassEnum\x12\x0c\n\x04rssi\x18\x03 \x01(\x11\x12\x14\n\x0crtls_payload\x18\x04 \x01(\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aruba_iot_nb_wifi_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WIFIDATA']._serialized_start=72
  _globals['_WIFIDATA']._serialized_end=186
# @@protoc_insertion_point(module_scope)
