# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-sb-action.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import aruba_iot_types_pb2 as aruba__iot__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61ruba-iot-sb-action.proto\x12\x0f\x61ruba_telemetry\x1a\x15\x61ruba-iot-types.proto\"\x89\x01\n\x0e\x41uthentication\x12\x35\n\x06method\x18\x01 \x01(\x0e\x32%.aruba_telemetry.AuthenticationMethod\x12\x0f\n\x07\x62onding\x18\x02 \x01(\x08\x12\x0f\n\x07passkey\x18\x03 \x01(\t\x12\x0e\n\x06keyOob\x18\x04 \x01(\x0c\x12\x0e\n\x06keyOwn\x18\x05 \x01(\x0c\"\xa6\x02\n\x06\x41\x63tion\x12\x10\n\x08\x61\x63tionId\x18\x01 \x01(\t\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.aruba_telemetry.ActionType\x12\x11\n\tdeviceMac\x18\x03 \x01(\x0c\x12\x13\n\x0bserviceUuid\x18\x04 \x01(\x0c\x12\x1a\n\x12\x63haracteristicUuid\x18\x05 \x01(\x0c\x12\x0f\n\x07timeOut\x18\x06 \x01(\r\x12\r\n\x05value\x18\x07 \x01(\x0c\x12\x37\n\x0e\x61uthentication\x18\x08 \x01(\x0b\x32\x1f.aruba_telemetry.Authentication\x12\x32\n\nbondingKey\x18\t \x01(\x0b\x32\x1e.aruba_telemetry.BleBondingKey\x12\x0e\n\x06\x61pbMac\x18\n \x01(\x0c*b\n\x14\x41uthenticationMethod\x12\x08\n\x04none\x10\x00\x12\x0b\n\x07passkey\x10\x01\x12\x07\n\x03oob\x10\x02\x12\x0c\n\x08lescNone\x10\x03\x12\x0f\n\x0blescPasskey\x10\x04\x12\x0b\n\x07lescOob\x10\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aruba_iot_sb_action_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUTHENTICATIONMETHOD']._serialized_start=506
  _globals['_AUTHENTICATIONMETHOD']._serialized_end=604
  _globals['_AUTHENTICATION']._serialized_start=70
  _globals['_AUTHENTICATION']._serialized_end=207
  _globals['_ACTION']._serialized_start=210
  _globals['_ACTION']._serialized_end=504
# @@protoc_insertion_point(module_scope)
