# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-sb-zb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import aruba_iot_zb_types_pb2 as aruba__iot__zb__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61ruba-iot-sb-zb.proto\x12\x0f\x61ruba_telemetry\x1a\x18\x61ruba-iot-zb-types.proto\"^\n\x08ZbSbSend\x12\r\n\x05reqid\x18\x01 \x01(\t\x12\x0b\n\x03mac\x18\x02 \x01(\x0c\x12%\n\x04\x65\x32pc\x18\x03 \x01(\x0b\x32\x17.aruba_telemetry.ZbE2PC\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\"\x19\n\x08ZbSbRead\x12\r\n\x05reqid\x18\x01 \x01(\t\"\x1a\n\tZbSbWrite\x12\r\n\x05reqid\x18\x01 \x01(\t\"\x1b\n\nZbSbAction\x12\r\n\x05reqid\x18\x01 \x01(\t\"\x8a\x01\n\x07ZbSbReq\x12\'\n\x04read\x18\x01 \x01(\x0b\x32\x19.aruba_telemetry.ZbSbRead\x12)\n\x05write\x18\x02 \x01(\x0b\x32\x1a.aruba_telemetry.ZbSbWrite\x12+\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32\x1b.aruba_telemetry.ZbSbAction\"p\n\x07SbZbMsg\x12\x11\n\tradio_mac\x18\x01 \x01(\x0c\x12\'\n\x04send\x18\x02 \x01(\x0b\x32\x19.aruba_telemetry.ZbSbSend\x12)\n\x07request\x18\x03 \x01(\x0b\x32\x18.aruba_telemetry.ZbSbReq')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aruba_iot_sb_zb_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ZBSBSEND']._serialized_start=68
  _globals['_ZBSBSEND']._serialized_end=162
  _globals['_ZBSBREAD']._serialized_start=164
  _globals['_ZBSBREAD']._serialized_end=189
  _globals['_ZBSBWRITE']._serialized_start=191
  _globals['_ZBSBWRITE']._serialized_end=217
  _globals['_ZBSBACTION']._serialized_start=219
  _globals['_ZBSBACTION']._serialized_end=246
  _globals['_ZBSBREQ']._serialized_start=249
  _globals['_ZBSBREQ']._serialized_end=387
  _globals['_SBZBMSG']._serialized_start=389
  _globals['_SBZBMSG']._serialized_end=501
# @@protoc_insertion_point(module_scope)
