# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-nb-status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aruba-iot-nb-status.proto',
  package='aruba_telemetry',
  serialized_pb=_b('\n\x19\x61ruba-iot-nb-status.proto\x12\x0f\x61ruba_telemetry\"_\n\x06Status\x12\x11\n\tdeviceMac\x18\x01 \x01(\x0c\x12,\n\x06status\x18\x02 \x01(\x0e\x32\x1c.aruba_telemetry.statusValue\x12\x14\n\x0cstatusString\x18\x03 \x01(\t*<\n\x0bstatusValue\x12\x16\n\x12\x64\x65viceDisconnected\x10\x00\x12\x15\n\x11inactivityTimeout\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_STATUSVALUE = _descriptor.EnumDescriptor(
  name='statusValue',
  full_name='aruba_telemetry.statusValue',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='deviceDisconnected', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='inactivityTimeout', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=143,
  serialized_end=203,
)
_sym_db.RegisterEnumDescriptor(_STATUSVALUE)

statusValue = enum_type_wrapper.EnumTypeWrapper(_STATUSVALUE)
deviceDisconnected = 0
inactivityTimeout = 1



_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='aruba_telemetry.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceMac', full_name='aruba_telemetry.Status.deviceMac', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='aruba_telemetry.Status.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statusString', full_name='aruba_telemetry.Status.statusString', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=141,
)

_STATUS.fields_by_name['status'].enum_type = _STATUSVALUE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['statusValue'] = _STATUSVALUE

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'aruba_iot_nb_status_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.Status)
  ))
_sym_db.RegisterMessage(Status)


# @@protoc_insertion_point(module_scope)
