# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-nb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import aruba_iot_types_pb2 as aruba__iot__types__pb2
import aruba_iot_nb_telemetry_pb2 as aruba__iot__nb__telemetry__pb2
import aruba_iot_nb_action_results_pb2 as aruba__iot__nb__action__results__pb2
import aruba_iot_nb_characteristic_pb2 as aruba__iot__nb__characteristic__pb2
import aruba_iot_nb_ble_data_pb2 as aruba__iot__nb__ble__data__pb2
import aruba_iot_nb_wifi_data_pb2 as aruba__iot__nb__wifi__data__pb2
import aruba_iot_nb_device_count_pb2 as aruba__iot__nb__device__count__pb2
import aruba_iot_nb_status_pb2 as aruba__iot__nb__status__pb2
import aruba_iot_nb_zb_pb2 as aruba__iot__nb__zb__pb2
import aruba_iot_nb_serial_data_pb2 as aruba__iot__nb__serial__data__pb2
import aruba_iot_nb_ap_health_update_pb2 as aruba__iot__nb__ap__health__update__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61ruba-iot-nb.proto\x12\x0f\x61ruba_telemetry\x1a\x15\x61ruba-iot-types.proto\x1a\x1c\x61ruba-iot-nb-telemetry.proto\x1a!aruba-iot-nb-action-results.proto\x1a!aruba-iot-nb-characteristic.proto\x1a\x1b\x61ruba-iot-nb-ble-data.proto\x1a\x1c\x61ruba-iot-nb-wifi-data.proto\x1a\x1f\x61ruba-iot-nb-device-count.proto\x1a\x19\x61ruba-iot-nb-status.proto\x1a\x15\x61ruba-iot-nb-zb.proto\x1a\x1e\x61ruba-iot-nb-serial-data.proto\x1a#aruba-iot-nb-ap-health-update.proto\"\x83\x01\n\x08Reporter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03mac\x18\x02 \x01(\x0c\x12\x0c\n\x04ipv4\x18\x03 \x01(\t\x12\x0c\n\x04ipv6\x18\x04 \x01(\t\x12\x0e\n\x06hwType\x18\x05 \x01(\t\x12\x11\n\tswVersion\x18\x06 \x01(\t\x12\x0f\n\x07swBuild\x18\x07 \x01(\t\x12\x0c\n\x04time\x18\x08 \x01(\x04\"\xb2\x04\n\tTelemetry\x12#\n\x04meta\x18\x01 \x02(\x0b\x32\x15.aruba_telemetry.Meta\x12+\n\x08reporter\x18\x02 \x02(\x0b\x32\x19.aruba_telemetry.Reporter\x12+\n\x08reported\x18\x03 \x03(\x0b\x32\x19.aruba_telemetry.Reported\x12.\n\x07results\x18\x04 \x03(\x0b\x32\x1d.aruba_telemetry.ActionResult\x12\x38\n\x0f\x63haracteristics\x18\x05 \x03(\x0b\x32\x1f.aruba_telemetry.Characteristic\x12)\n\x07\x62leData\x18\x06 \x03(\x0b\x32\x18.aruba_telemetry.BleData\x12+\n\x08wifiData\x18\x07 \x03(\x0b\x32\x19.aruba_telemetry.WiFiData\x12.\n\x08\x64\x65vCount\x18\x08 \x01(\x0b\x32\x1c.aruba_telemetry.DeviceCount\x12\'\n\x06status\x18\t \x01(\x0b\x32\x17.aruba_telemetry.Status\x12(\n\x06zigbee\x18\n \x01(\x0b\x32\x18.aruba_telemetry.NbZbMsg\x12.\n\x07nbSData\x18\x0b \x03(\x0b\x32\x1d.aruba_telemetry.NbSerialData\x12\x31\n\x08\x61pHealth\x18\x0c \x01(\x0b\x32\x1f.aruba_telemetry.ApHealthUpdate')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aruba_iot_nb_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REPORTER']._serialized_start=374
  _globals['_REPORTER']._serialized_end=505
  _globals['_TELEMETRY']._serialized_start=508
  _globals['_TELEMETRY']._serialized_end=1070
# @@protoc_insertion_point(module_scope)
