# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-nb-device-count.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import aruba_iot_types_pb2 as aruba__iot__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61ruba-iot-nb-device-count.proto\x12\x0f\x61ruba_telemetry\x1a\x15\x61ruba-iot-types.proto\"\xfa\x04\n\x0b\x44\x65viceCount\x12\x18\n\x10\x64\x65v_unclassified\x18\x01 \x01(\x05\x12\x17\n\x0f\x64\x65v_arubaBeacon\x18\x02 \x01(\x05\x12\x14\n\x0c\x64\x65v_arubaTag\x18\x03 \x01(\x05\x12\x11\n\tdev_zfTag\x18\x04 \x01(\x05\x12\x16\n\x0e\x64\x65v_stanleyTag\x18\x05 \x01(\x05\x12\x18\n\x10\x64\x65v_virginBeacon\x18\x06 \x01(\x05\x12\x19\n\x11\x64\x65v_enoceanSensor\x18\x07 \x01(\x05\x12\x19\n\x11\x64\x65v_enoceanSwitch\x18\x08 \x01(\x05\x12\x13\n\x0b\x64\x65v_iBeacon\x18\t \x01(\x05\x12\x16\n\x0e\x64\x65v_allBleData\x18\n \x01(\x05\x12\x16\n\x0e\x64\x65v_RawBleData\x18\x0b \x01(\x05\x12\x15\n\rdev_eddystone\x18\x0c \x01(\x05\x12\x15\n\rdev_assaAbloy\x18\r \x01(\x05\x12\x17\n\x0f\x64\x65v_arubaSensor\x18\x0e \x01(\x05\x12\x15\n\rdev_abbSensor\x18\x0f \x01(\x05\x12\x13\n\x0b\x64\x65v_wifiTag\x18\x10 \x01(\x05\x12\x18\n\x10\x64\x65v_wifiAssocSta\x18\x11 \x01(\x05\x12\x1a\n\x12\x64\x65v_wifiUnassocSta\x18\x12 \x01(\x05\x12\x14\n\x0c\x64\x65v_mysphera\x18\x13 \x01(\x05\x12\x13\n\x0b\x64\x65v_sBeacon\x18\x14 \x01(\x05\x12\x11\n\tdev_onity\x18\x15 \x01(\x05\x12\x11\n\tdev_minew\x18\x16 \x01(\x05\x12\x12\n\ndev_google\x18\x17 \x01(\x05\x12\x14\n\x0c\x64\x65v_polestar\x18\x18 \x01(\x05\x12\x12\n\ndev_blyott\x18\x19 \x01(\x05\x12\x12\n\ndev_diract\x18\x1a \x01(\x05\x12\x16\n\x0e\x64\x65v_gwahygiene\x18\x1b \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aruba_iot_nb_device_count_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEVICECOUNT']._serialized_start=76
  _globals['_DEVICECOUNT']._serialized_end=710
# @@protoc_insertion_point(module_scope)
