# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-nb-ap-health-update.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#aruba-iot-nb-ap-health-update.proto\x12\x0f\x61ruba_telemetry\"\xbe\x01\n\x08IotRadio\x12\x0b\n\x03mac\x18\x01 \x01(\x0c\x12/\n\x08hardware\x18\x02 \x01(\x0e\x32\x1d.aruba_telemetry.IotRadioType\x12\x33\n\x08\x66irmware\x18\x03 \x01(\x0e\x32!.aruba_telemetry.IotRadioFirmware\x12-\n\x06health\x18\x04 \x01(\x0e\x32\x1d.aruba_telemetry.HealthStatus\x12\x10\n\x08\x65xternal\x18\x05 \x01(\x08\"N\n\tUsbDevice\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12-\n\x06health\x18\x02 \x01(\x0e\x32\x1d.aruba_telemetry.HealthStatus\"\x94\x01\n\x0e\x41pHealthUpdate\x12/\n\x08\x61pStatus\x18\x01 \x01(\x0e\x32\x1d.aruba_telemetry.HealthStatus\x12(\n\x05radio\x18\x02 \x03(\x0b\x32\x19.aruba_telemetry.IotRadio\x12\'\n\x03usb\x18\x03 \x03(\x0b\x32\x1a.aruba_telemetry.UsbDevice*:\n\x0cHealthStatus\x12\x0b\n\x07healthy\x10\x00\x12\x0c\n\x08\x64\x65graded\x10\x01\x12\x0f\n\x0bunavailable\x10\x02*$\n\x10IotRadioFirmware\x12\x10\n\x0c\x61rubaDefault\x10\x00*\"\n\x0cIotRadioType\x12\x08\n\x04gen1\x10\x00\x12\x08\n\x04gen2\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aruba_iot_nb_ap_health_update_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEALTHSTATUS']._serialized_start=480
  _globals['_HEALTHSTATUS']._serialized_end=538
  _globals['_IOTRADIOFIRMWARE']._serialized_start=540
  _globals['_IOTRADIOFIRMWARE']._serialized_end=576
  _globals['_IOTRADIOTYPE']._serialized_start=578
  _globals['_IOTRADIOTYPE']._serialized_end=612
  _globals['_IOTRADIO']._serialized_start=57
  _globals['_IOTRADIO']._serialized_end=247
  _globals['_USBDEVICE']._serialized_start=249
  _globals['_USBDEVICE']._serialized_end=327
  _globals['_APHEALTHUPDATE']._serialized_start=330
  _globals['_APHEALTHUPDATE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
