# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-nb-status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61ruba-iot-nb-status.proto\x12\x0f\x61ruba_telemetry\"\x1f\n\nConnUpdate\x12\x11\n\tmtu_value\x18\x01 \x01(\r\"\x90\x01\n\x06Status\x12\x11\n\tdeviceMac\x18\x01 \x01(\x0c\x12,\n\x06status\x18\x02 \x01(\x0e\x32\x1c.aruba_telemetry.statusValue\x12\x14\n\x0cstatusString\x18\x03 \x01(\t\x12/\n\nconnUpdate\x18\x04 \x01(\x0b\x32\x1b.aruba_telemetry.ConnUpdate*R\n\x0bstatusValue\x12\x16\n\x12\x64\x65viceDisconnected\x10\x00\x12\x15\n\x11inactivityTimeout\x10\x01\x12\x14\n\x10\x63onnectionUpdate\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aruba_iot_nb_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSVALUE']._serialized_start=226
  _globals['_STATUSVALUE']._serialized_end=308
  _globals['_CONNUPDATE']._serialized_start=46
  _globals['_CONNUPDATE']._serialized_end=77
  _globals['_STATUS']._serialized_start=80
  _globals['_STATUS']._serialized_end=224
# @@protoc_insertion_point(module_scope)
