# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-sb-action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import aruba_iot_types_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aruba-iot-sb-action.proto',
  package='aruba_telemetry',
  serialized_pb=_b('\n\x19\x61ruba-iot-sb-action.proto\x12\x0f\x61ruba_telemetry\x1a\x15\x61ruba-iot-types.proto\"\xa9\x01\n\x06\x41\x63tion\x12\x10\n\x08\x61\x63tionId\x18\x01 \x01(\t\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.aruba_telemetry.ActionType\x12\x11\n\tdeviceMac\x18\x03 \x01(\x0c\x12\x13\n\x0bserviceUuid\x18\x04 \x01(\x0c\x12\x1a\n\x12\x63haracteristicUuid\x18\x05 \x01(\x0c\x12\x0f\n\x07timeOut\x18\x06 \x01(\r\x12\r\n\x05value\x18\x07 \x01(\x0c')
  ,
  dependencies=[aruba_iot_types_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='aruba_telemetry.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actionId', full_name='aruba_telemetry.Action.actionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='aruba_telemetry.Action.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceMac', full_name='aruba_telemetry.Action.deviceMac', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serviceUuid', full_name='aruba_telemetry.Action.serviceUuid', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='characteristicUuid', full_name='aruba_telemetry.Action.characteristicUuid', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeOut', full_name='aruba_telemetry.Action.timeOut', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='aruba_telemetry.Action.value', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=239,
)

_ACTION.fields_by_name['type'].enum_type = aruba_iot_types_pb2._ACTIONTYPE
DESCRIPTOR.message_types_by_name['Action'] = _ACTION

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(
  DESCRIPTOR = _ACTION,
  __module__ = 'aruba_iot_sb_action_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.Action)
  ))
_sym_db.RegisterMessage(Action)


# @@protoc_insertion_point(module_scope)
